version: '3.8'

services:
  mysql-db:
    image: mysql:8.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookdb
    ports:
      - "3306:3306"
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: springboot-bookcrud
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bookdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

networks:
  app-net:
